const GAME_KEY="ecoGameSession_v4";const TOTAL_TIME=7*60;const CHALLENGE_NO=4;
const AREAS=[
 {title:"🌳 Area 1: Taman",hint:"Cari sesuatu yang membuat taman hijau dan bersih.",objects:[
  ['tree',18,28,'🌳','Pohon',true,'Pohon membantu lingkungan menjadi hijau dan menyediakan tempat hidup bagi makhluk.'],['flower',38,38,'🌼','Bunga',true,'Bunga merupakan bagian dari tumbuhan dan dapat membantu ekosistem.'],['bin',60,30,'🗑️','Tempat sampah',true,'Tempat sampah membantu sampah tidak berserakan.'],['water',78,43,'💧','Air',true,'Tanaman dan hewan membutuhkan air untuk hidup.'],['car',29,63,'🚗','Mobil',false,'Mobil bukan benda yang sedang kita cari di taman.'],['plastic',50,68,'🛍️','Plastik',false,'Sampah plastik bukan benda baik untuk ditemukan berserakan di taman.'],['rock',70,63,'🪨','Batu',false,'Batu bisa ada di taman, tetapi bukan salah satu benda baik yang harus ditemukan dalam misi ini.'],['candy',84,71,'🍬','Permen',false,'Permen bukan benda yang membantu menjaga taman.'] ]},
 {title:"🏞️ Area 2: Sungai",hint:"Cari benda yang membantu air tetap bersih dan makhluk hidup aman.",objects:[
  ['fish',17,34,'🐟','Ikan',true,'Ikan membutuhkan air yang bersih dan merupakan bagian dari ekosistem sungai.'],['water',37,55,'💧','Air bersih',true,'Air bersih sangat penting bagi hewan, tumbuhan, dan manusia.'],['plant',58,32,'🌿','Tanaman',true,'Tumbuhan di tepi sungai dapat menjadi bagian penting dari ekosistem.'],['bin',80,40,'🗑️','Tempat sampah',true,'Tempat sampah membantu sampah tidak masuk ke sungai.'],['bottle',28,72,'🧴','Botol bekas',false,'Botol bekas menjadi sampah jika tidak dikelola dengan baik.'],['tire',48,74,'🛞','Ban bekas',false,'Ban bekas bukan benda yang seharusnya berada di sungai.'],['oil',68,68,'🛢️','Minyak',false,'Minyak dapat mencemari air dan mengganggu kehidupan di sungai.'],['smoke',85,69,'💨','Asap',false,'Asap bukan tanda sungai yang sehat.'] ]},
 {title:"🏡 Area 3: Rumah",hint:"Cari kebiasaan atau benda yang membantu menghemat sumber daya di rumah.",objects:[
  ['light',16,32,'💡','Matikan lampu',true,'Mematikan lampu saat tidak digunakan membantu menghemat listrik.'],['faucet',37,54,'🚰','Tutup keran',true,'Menutup keran saat tidak digunakan membantu menghemat air.'],['bag',59,30,'👜','Tas pakai ulang',true,'Tas pakai ulang dapat mengurangi kebutuhan kantong sekali pakai.'],['bottle',80,43,'🥤','Botol pakai ulang',true,'Botol pakai ulang dapat mengurangi sampah dari botol sekali pakai.'],['tv',24,72,'📺','TV menyala',false,'TV yang tidak digunakan sebaiknya dimatikan untuk menghemat listrik.'],['tap',47,75,'💦','Keran terbuka',false,'Keran terbuka membuat air terbuang sia-sia.'],['bagplastic',69,69,'🛍️','Kantong plastik',false,'Kantong sekali pakai dapat menambah sampah plastik.'],['trash',87,70,'🗑️','Sampah berserakan',false,'Sampah yang berserakan perlu dipilah dan ditempatkan dengan benar.'] ]}
];
let session=null,timerHandle=null,hintTimer=null;
const $=id=>document.getElementById(id);const tutorialScreen=$("tutorialScreen"),gameArea=$("gameArea"),resultScreen=$("resultScreen"),timeoutScreen=$("timeoutScreen"),progressText=$("progressText"),timerText=$("timerText"),areaTitle=$("areaTitle"),areaProgress=$("areaProgress"),explorationObjects=$("explorationObjects"),sceneSpeech=$("sceneSpeech"),areaDots=$("areaDots"),feedback=$("feedback"),feedbackIcon=$("feedbackIcon"),feedbackTitle=$("feedbackTitle"),feedbackText=$("feedbackText"),hintBox=$("hintBox");
function load(){try{return JSON.parse(localStorage.getItem(GAME_KEY)||"null")}catch{return null}}function save(){localStorage.setItem(GAME_KEY,JSON.stringify(session))}
function syncTime(){if(!session||session.status!=="playing")return;const now=Date.now(),elapsed=Math.floor((now-session.lastUpdatedAt)/1000);if(elapsed<=0)return;session.timeRemaining=Math.max(0,session.timeRemaining-elapsed);session.lastUpdatedAt=now;if(session.timeRemaining===0){session.status="timeup";save();showTimeout();return}save();updateHud()}
function startTimer(){clearInterval(timerHandle);syncTime();timerHandle=setInterval(syncTime,250);document.addEventListener('visibilitychange',syncTime)}
function updateHud(){const found=totalFound();progressText.textContent=`${found}/12`;const sec=Math.max(0,session.timeRemaining);timerText.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;timerText.style.color=sec<=30?'#d65f50':sec<=60?'#bd8b23':''}
function totalFound(){return (session.exploration?.found||[]).reduce((sum,a)=>sum+a.length,0)}
function showFeedback(icon,title,text,type){feedbackIcon.textContent=icon;feedbackTitle.textContent=title;feedbackText.textContent=text;feedback.className=`feedback ${type==='correct'?'correct-feedback':'wrong-feedback'}`}
function hideFeedback(){feedback.classList.add('hidden')}
function showHint(){const area=AREAS[session.exploration.area];hintBox.textContent=`💡 ${area.hint}`;hintBox.classList.remove('hidden');clearTimeout(hintTimer);hintTimer=setTimeout(()=>hintBox.classList.add('hidden'),4500)}
function resetHint(){clearTimeout(hintTimer);hintBox.classList.add('hidden');hintTimer=setTimeout(()=>{if(session.status==='playing')showHint()},12000)}
function ensure(){session=load();if(!session||session.version!==4||session.currentChallenge!==CHALLENGE_NO){if(session&&session.currentChallenge>=1&&session.currentChallenge<CHALLENGE_NO){location.href=`challenge${session.currentChallenge}.html`;return false}location.href='challenge1.html';return false}if(session.status==='completed'){renderResult();return false}if(session.status==='timeup'||session.timeRemaining<=0){session.status='timeup';save();showTimeout();return false}return true}
function startChallenge(){session.challengeStarted[3]=true;session.status='playing';session.lastUpdatedAt=Date.now();if(!session.exploration)session.exploration={area:0,found:[[],[],[]]};save();tutorialScreen.classList.add('hidden');gameArea.classList.remove('hidden');renderArea();startTimer();resetHint()}
function renderArea(){
  const area=AREAS[session.exploration.area];areaTitle.textContent=area.title;areaProgress.textContent=`Temukan 4 benda baik di area ini (${session.exploration.found[session.exploration.area].length}/4).`;sceneSpeech.textContent=`Cari 4 benda baik di ${area.title.replace(/^\S+\s/,'')}! 👀`;
  explorationObjects.innerHTML='';const found=new Set(session.exploration.found[session.exploration.area]);
  area.objects.forEach(o=>{const [id,x,y,icon,label,correct,explanation]=o,b=document.createElement('button');b.type='button';b.className=`explore-object ${found.has(id)?'found':''}`;b.style.left=`${x}%`;b.style.top=`${y}%`;b.dataset.id=id;b.innerHTML=`<span class="explore-icon">${icon}</span><span class="explore-label">${label}</span>`;b.addEventListener('click',()=>pickObject(b,o));explorationObjects.appendChild(b)});
  areaDots.innerHTML=AREAS.map((_,i)=>`<span class="area-dot ${i===session.exploration.area?'active ':''}${session.exploration.found[i]?.length>=4?'done':''}"></span>`).join('');updateHud();save();resetHint();
}
function pickObject(button,o){if(session.status!=='playing'||button.classList.contains('found'))return;clearTimeout(hintTimer);const [id,x,y,icon,label,correct,explanation]=o;if(correct){session.totalCorrect++;session.score+=5;session.exploration.found[session.exploration.area].push(id);button.classList.add('found');showFeedback('🎉','Benar!',explanation,'correct');sceneSpeech.textContent='Bagus! Temuan yang tepat! 🌱';save();updateHud();
  setTimeout(()=>{hideFeedback();const count=session.exploration.found[session.exploration.area].length;if(count>=4)nextArea();else{areaProgress.textContent=`Temukan 4 benda baik di area ini (${count}/4).`;resetHint()}},850)
}else{session.totalWrong++;button.classList.add('miss');save();showFeedback('💡','Belum tepat',explanation,'wrong');sceneSpeech.textContent='Tidak apa-apa. Cari yang lain ya! 😊';setTimeout(()=>{button.classList.remove('miss');hideFeedback();resetHint()},1100)}}
function nextArea(){
  const current=session.exploration.area;if(current<AREAS.length-1){session.exploration.area++;save();setTimeout(renderArea,600)}else{completeGame()}
}
function calculateScore(){return session.score+Math.floor(Math.max(0,session.timeRemaining)/5)}
function stars(){const done=totalFound();if(done>=12)return 3;if(done>=8)return 2;if(done>=4)return 1;return 0}
function completeGame(){clearTimeout(hintTimer);session.completed[3]=true;session.currentChallenge=4;session.status='completed';session.score+=100;session.lastUpdatedAt=Date.now();save();clearInterval(timerHandle);renderResult()}
function renderResult(){tutorialScreen.classList.add('hidden');gameArea.classList.add('hidden');timeoutScreen.classList.add('hidden');resultScreen.classList.remove('hidden');const starCount=3;$("resultStars").textContent='🌟 '.repeat(starCount).trim();$("finalScore").textContent=calculateScore();$("finalProgress").textContent='4/4';const sec=Math.max(0,session.timeRemaining);$("finalTime").textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$("resultMessage").textContent=`Kamu menemukan ${totalFound()} benda baik dan menyelesaikan seluruh petualangan. Keren sekali! 🌍`}
function showTimeout(){clearTimeout(hintTimer);clearInterval(timerHandle);gameArea.classList.add('hidden');tutorialScreen.classList.add('hidden');resultScreen.classList.add('hidden');timeoutScreen.classList.remove('hidden')}
function restart(){localStorage.removeItem(GAME_KEY);location.href='challenge1.html'}
function checkStartup(){if(!ensure()){if(session?.status==='completed')renderResult();return}if(!session.exploration)session.exploration={area:0,found:[[],[],[]]};updateHud();if(session.challengeStarted[3]){tutorialScreen.classList.add('hidden');gameArea.classList.remove('hidden');renderArea();startTimer()}else{tutorialScreen.classList.remove('hidden');gameArea.classList.add('hidden');clearInterval(timerHandle)}}
$("startChallengeBtn").addEventListener('click',startChallenge);$("hintBtn").addEventListener('click',()=>{if(session?.status==='playing')showHint()});$("restartBtn").addEventListener('click',restart);$("retryBtn").addEventListener('click',restart);window.addEventListener('beforeunload',()=>{if(session){syncTime();save()}});checkStartup();
