const GAME_KEY="ecoGameSession_v4";const TOTAL_TIME=7*60;const CHALLENGE_NO=2;const nextPage="challenge3.html";
const QUESTIONS=[
 {q:"Apa yang dibutuhkan tanaman agar tidak layu?",i:"🌱",o:[['Air','💧',true,'Tanaman membutuhkan air agar tetap segar dan tumbuh.'],['Batu','🪨',false,'Batu bukan pengganti kebutuhan tanaman akan air.'],['Plastik','🛍️',false,'Plastik bukan kebutuhan tanaman.']],h:"Sesuatu yang cair dan biasa disiramkan ke tanaman."},
 {q:"Mana yang termasuk tumbuhan?",i:"🌳",o:[['Pohon','🌳',true,'Pohon adalah salah satu jenis tumbuhan.'],['Mobil','🚗',false,'Mobil adalah benda buatan manusia.'],['Bola','⚽',false,'Bola bukan tumbuhan.']],h:"Cari sesuatu yang memiliki batang dan daun."},
 {q:"Ke mana sebaiknya kulit pisang dibuang?",i:"🍌",o:[['Organik','🟩',true,'Kulit pisang berasal dari tumbuhan dan termasuk organik.'],['Plastik','🟦',false,'Kulit pisang bukan plastik.'],['Kertas','🟨',false,'Kulit pisang bukan kertas.']],h:"Pikirkan: benda ini berasal dari tumbuhan atau bukan?"},
 {q:"Apa yang membantu udara di sekitar rumah terasa lebih segar?",i:"🏡",o:[['Pohon','🌳',true,'Pohon membantu menghasilkan oksigen dan membuat lingkungan lebih nyaman.'],['Sampah','🗑️',false,'Sampah yang berserakan justru membuat lingkungan kotor.'],['Asap','💨',false,'Asap dapat membuat udara menjadi tidak sehat.']],h:"Cari sesuatu yang hijau dan memiliki daun."},
 {q:"Apa kebiasaan baik saat selesai memakai keran?",i:"🚰",o:[['Menutup keran','✅',true,'Menutup keran membantu menghemat air.'],['Membiarkannya terbuka','💦',false,'Keran terbuka membuat air terus terbuang.'],['Membuatnya menetes','💧',false,'Air yang terus menetes juga terbuang.']],h:"Air akan hemat kalau alirannya dihentikan."},
 {q:"Benda mana yang bisa dipakai berulang kali untuk mengurangi sampah plastik?",i:"🧃",o:[['Botol minum','🥤',true,'Botol minum dapat digunakan berulang kali.'],['Sedotan sekali pakai','🥤',false,'Sedotan sekali pakai menjadi sampah setelah digunakan.'],['Kantong plastik sekali pakai','🛍️',false,'Kantong sekali pakai lebih cepat menjadi sampah.']],h:"Pilih benda yang bisa dipakai lagi dan lagi."},
 {q:"Daun kering dapat dimanfaatkan menjadi apa?",i:"🍂",o:[['Kompos','🌱',true,'Daun kering dapat diolah menjadi bahan kompos.'],['Asap','💨',false,'Membakar daun membuat asap dan bukan cara terbaik untuk memanfaatkannya.'],['Plastik','🛍️',false,'Daun tidak berubah menjadi plastik.']],h:"Kompos adalah pupuk dari bahan alami yang terurai."},
 {q:"Apa yang sebaiknya kita lakukan saat melihat sampah di lantai?",i:"🗑️",o:[['Memungut dan memilah','🧤',true,'Memungut dan memilah sampah membantu lingkungan tetap bersih.'],['Mendorong dengan kaki','🦶',false,'Sampah tetap berada di tempat yang tidak semestinya.'],['Membiarkannya','🙈',false,'Sampah yang dibiarkan dapat membuat lingkungan kotor.']],h:"Bayangkan kamu ingin membuat lantai bersih."},
 {q:"Apa yang dapat terjadi jika banyak sampah masuk ke sungai?",i:"🏞️",o:[['Air menjadi kotor','💧',true,'Sampah dapat mengotori air dan mengganggu hewan di sungai.'],['Air menjadi permen','🍬',false,'Air tidak berubah menjadi permen.'],['Ikan menjadi robot','🤖',false,'Sampah tidak membuat ikan menjadi robot.']],h:"Coba pikirkan kondisi sungai yang penuh sampah."},
 {q:"Saat keluar dari ruangan, apa yang dapat membantu menghemat listrik?",i:"💡",o:[['Mematikan lampu','💡',true,'Lampu yang tidak dipakai sebaiknya dimatikan untuk menghemat listrik.'],['Menyalakan semua lampu','✨',false,'Menyalakan lampu yang tidak diperlukan memakai lebih banyak listrik.'],['Membiarkan TV menyala','📺',false,'TV yang tidak digunakan tetap memakai listrik.']],h:"Yang tidak dipakai sebaiknya dimatikan."},
 {q:"Mana yang lebih baik untuk membawa belanjaan agar mengurangi kantong plastik?",i:"🛒",o:[['Tas belanja pakai ulang','👜',true,'Tas pakai ulang dapat digunakan berkali-kali.'],['Kantong plastik baru setiap kali','🛍️',false,'Cara ini menghasilkan lebih banyak sampah plastik.'],['Membawa banyak sedotan','🥤',false,'Sedotan bukan pengganti tas belanja.']],h:"Pilih tas yang bisa dipakai berkali-kali."},
 {q:"Hewan membutuhkan lingkungan seperti apa?",i:"🐟",o:[['Bersih dan aman','🌿',true,'Hewan membutuhkan tempat hidup yang bersih dan aman.'],['Penuh sampah','🗑️',false,'Sampah dapat mengganggu tempat hidup hewan.'],['Penuh asap','💨',false,'Asap dapat membuat lingkungan tidak sehat.']],h:"Hewan juga membutuhkan rumah yang nyaman."},
 {q:"Apa yang dapat kita lakukan untuk membantu pohon tumbuh?",i:"🌳",o:[['Merawatnya dengan air','💧',true,'Tanaman perlu dirawat dengan air yang cukup dan lingkungan yang baik.'],['Mematahkan dahan','🪵',false,'Merusak dahan dapat melukai pohon.'],['Menutupinya dengan plastik','🛍️',false,'Plastik bukan cara merawat pohon.']],h:"Tanaman perlu dirawat, bukan dirusak."},
 {q:"Kertas bekas yang masih bisa digunakan sebaiknya bagaimana?",i:"📄",o:[['Gunakan sisi yang masih kosong','✏️',true,'Memakai kembali sisi kosong membantu mengurangi penggunaan kertas baru.'],['Langsung dibuang','🗑️',false,'Masih ada sisi yang bisa dipakai.'],['Disiram air','💦',false,'Air tidak membuat kertas bekas menjadi lebih berguna.']],h:"Lihat apakah masih ada sisi kosong."},
 {q:"Cara sederhana menjaga air tetap bersih adalah...",i:"💧",o:[['Tidak membuang sampah ke sungai','🚯',true,'Sungai perlu dijaga agar tidak tercemar sampah.'],['Melempar plastik ke sungai','🛍️',false,'Plastik dapat mencemari air dan membahayakan hewan.'],['Membuang minyak ke sungai','🧴',false,'Minyak dapat mencemari air.']],h:"Sungai adalah rumah bagi banyak makhluk hidup."},
 {q:"Mana yang membantu menjaga kebersihan taman?",i:"🌼",o:[['Memakai tempat sampah','🗑️',true,'Tempat sampah membantu sampah tidak berserakan.'],['Meninggalkan bungkus makanan','🍬',false,'Sampah yang ditinggalkan membuat taman kotor.'],['Menginjak tanaman','👟',false,'Tanaman perlu dijaga, bukan diinjak.']],h:"Cari benda yang membantu sampah berada di tempatnya."},
 {q:"Saat siang hari yang terang, apa yang bisa membantu menghemat listrik di dalam kelas?",i:"☀️",o:[['Memakai cahaya matahari','☀️',true,'Cahaya alami dapat mengurangi kebutuhan menyalakan lampu.'],['Menyalakan semua lampu','💡',false,'Lampu tidak perlu dinyalakan jika cahaya sudah cukup.'],['Menyalakan banyak TV','📺',false,'TV memakai listrik dan tidak membantu pencahayaan.']],h:"Lihat sumber cahaya alami dari luar."},
 {q:"Mana kegiatan yang lebih ramah lingkungan untuk jarak dekat?",i:"🚲",o:[['Berjalan kaki','🚶',true,'Berjalan kaki tidak menghasilkan asap kendaraan.'],['Menyalakan banyak mobil','🚗',false,'Lebih banyak kendaraan dapat menghasilkan lebih banyak emisi.'],['Membiarkan mesin menyala','🚘',false,'Mesin yang menyala tetap memakai bahan bakar.']],h:"Kegiatan tanpa mesin kendaraan bisa lebih ramah lingkungan."},
 {q:"Apa yang sebaiknya dilakukan pada botol plastik yang bisa didaur ulang?",i:"🧴",o:[['Dipilah untuk didaur ulang','♻️',true,'Botol plastik yang sesuai dapat dipilah agar bisa dikelola atau didaur ulang.'],['Dilempar ke sungai','🏞️',false,'Sungai bukan tempat membuang sampah.'],['Ditinggalkan di taman','🌳',false,'Sampah sebaiknya tidak dibiarkan berserakan.']],h:"Cari simbol yang berarti dapat diolah kembali."},
 {q:"Mengapa menanam banyak tumbuhan baik untuk lingkungan?",i:"🌱",o:[['Membantu lingkungan menjadi lebih hijau','🌿',true,'Tumbuhan membantu membuat lingkungan lebih hijau dan menyediakan habitat bagi makhluk hidup.'],['Membuat sampah bertambah','🗑️',false,'Menanam tumbuhan tidak membuat sampah otomatis bertambah.'],['Mengotori air','💧',false,'Tumbuhan bukan penyebab air menjadi kotor.']],h:"Bayangkan halaman yang penuh tanaman sehat."}
];
let session=null,timerHandle=null,hintTimer=null;
const $=id=>document.getElementById(id);const tutorialScreen=$("tutorialScreen"),gameArea=$("gameArea"),timeoutScreen=$("timeoutScreen"),progressText=$("progressText"),timerText=$("timerText"),questionProgress=$("questionProgress"),questionText=$("questionText"),illustration=$("illustration"),options=$("options"),feedback=$("feedback"),feedbackIcon=$("feedbackIcon"),feedbackTitle=$("feedbackTitle"),feedbackText=$("feedbackText"),hintBox=$("hintBox");
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function load(){try{return JSON.parse(localStorage.getItem(GAME_KEY)||"null")}catch{return null}}
function save(){localStorage.setItem(GAME_KEY,JSON.stringify(session))}
function syncTime(){if(!session||session.status!=="playing")return;const now=Date.now(),elapsed=Math.floor((now-session.lastUpdatedAt)/1000);if(elapsed<=0)return;session.timeRemaining=Math.max(0,session.timeRemaining-elapsed);session.lastUpdatedAt=now;if(session.timeRemaining===0){session.status="timeup";save();showTimeout();return}save();updateHud()}
function startTimer(){clearInterval(timerHandle);syncTime();timerHandle=setInterval(syncTime,250);document.addEventListener("visibilitychange",syncTime)}
function updateHud(){const q=session.quiz?.pos??0;progressText.textContent=`${q}/15`;const sec=Math.max(0,session.timeRemaining??0);timerText.textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`;timerText.style.color=sec<=30?"#d65f50":sec<=60?"#bd8b23":""}
function showFeedback(icon,title,text,type){feedbackIcon.textContent=icon;feedbackTitle.textContent=title;feedbackText.textContent=text;feedback.className=`feedback ${type==='correct'?'correct-feedback':'wrong-feedback'}`}
function hideFeedback(){feedback.classList.add("hidden")}
function showHint(){const q=QUESTIONS[session.quiz.sequence[session.quiz.pos]];hintBox.textContent=q.h;hintBox.classList.remove("hidden");clearTimeout(hintTimer);hintTimer=setTimeout(()=>hintBox.classList.add("hidden"),4500)}
function resetHintTimer(){clearTimeout(hintTimer);hintBox.classList.add("hidden");hintTimer=setTimeout(()=>{if(session.status==='playing')showHint()},11000)}
function ensure(){session=load();if(!session||session.version!==4||session.currentChallenge!==CHALLENGE_NO){if(session&&session.currentChallenge>CHALLENGE_NO){location.href=`challenge${session.currentChallenge}.html`;return false}location.href="challenge1.html";return false}if(session.status==='timeup'||session.timeRemaining<=0){session.status='timeup';save();showTimeout();return false}return true}
function initQuiz(){
  if(!session.quiz||!Array.isArray(session.quiz.sequence)||session.quiz.sequence.length!==15){session.quiz={sequence:shuffle(QUESTIONS.map((_,i)=>i)).slice(0,15),pos:0,optionOrder:shuffle([0,1,2])};save()}
  if(session.quiz.pos>=15){completeChallenge();return}
}
function startChallenge(){session.challengeStarted[1]=true;session.started=true;session.status='playing';session.lastUpdatedAt=Date.now();if(!session.quiz)session.quiz={sequence:shuffle(QUESTIONS.map((_,i)=>i)).slice(0,15),pos:0,optionOrder:shuffle([0,1,2])};save();tutorialScreen.classList.add('hidden');gameArea.classList.remove('hidden');renderQuestion();updateHud();startTimer();resetHintTimer()}
function renderQuestion(){
  const q=QUESTIONS[session.quiz.sequence[session.quiz.pos]];questionProgress.textContent=`Pertanyaan ${session.quiz.pos+1} dari 15`;questionText.textContent=q.q;illustration.textContent=q.i;options.innerHTML="";
  if(!Array.isArray(session.quiz.optionOrder)||session.quiz.optionOrder.length!==3)session.quiz.optionOrder=shuffle([0,1,2]);
  session.quiz.optionOrder.forEach(index=>{const [label,icon,correct,explanation]=q.o[index];const b=document.createElement('button');b.type='button';b.className='quiz-option';b.innerHTML=`<span class="quiz-option-icon">${icon}</span><span class="quiz-option-label">${label}</span>`;b.addEventListener('click',()=>answer(b,{label,icon,correct,explanation}));options.appendChild(b)})
  save();resetHintTimer();
}
function answer(button,opt){if(session.status!=='playing'||button.classList.contains('locked'))return;clearTimeout(hintTimer);session.totalWrong += opt.correct?0:1;
  if(opt.correct){session.totalCorrect++;session.score+=5;button.classList.add('correct');options.querySelectorAll('.quiz-option').forEach(b=>b.classList.add('locked'));save();showFeedback('🎉','Benar!',opt.explanation,'correct');
    setTimeout(()=>{hideFeedback();session.quiz.pos++;session.quiz.optionOrder=shuffle([0,1,2]);save();updateHud();if(session.quiz.pos>=15)completeChallenge();else renderQuestion()},900)
  }else{button.classList.add('wrong');save();showFeedback('💡','Belum tepat',opt.explanation,'wrong');setTimeout(()=>{button.classList.remove('wrong');hideFeedback();resetHintTimer()},1200)}
}
function completeChallenge(){clearTimeout(hintTimer);session.completed[1]=true;session.score+=100;session.currentChallenge=3;session.challengeStarted[2]=false;session.status='instruction';session.lastUpdatedAt=Date.now();save();gameArea.classList.add('hidden');setTimeout(()=>location.href=nextPage,900)}
function showTimeout(){clearTimeout(hintTimer);clearInterval(timerHandle);gameArea.classList.add('hidden');tutorialScreen.classList.add('hidden');timeoutScreen.classList.remove('hidden')}
function restart(){localStorage.removeItem(GAME_KEY);location.href='challenge1.html'}
function checkStartup(){if(!ensure())return;updateHud();initQuiz();if(session.status==='timeup')return;if(session.challengeStarted[1]){tutorialScreen.classList.add('hidden');gameArea.classList.remove('hidden');renderQuestion();startTimer()}else{tutorialScreen.classList.remove('hidden');gameArea.classList.add('hidden');clearInterval(timerHandle)}}
$("startChallengeBtn").addEventListener('click',startChallenge);$("hintBtn").addEventListener('click',()=>{if(session?.status==='playing')showHint()});document.querySelector('[data-restart]').addEventListener('click',restart);window.addEventListener('beforeunload',()=>{if(session){syncTime();save()}});checkStartup();
