const GAME_KEY="ecoGameSession_v4";const TOTAL_TIME=7*60;const CHALLENGE_NO=3;const nextPage="challenge4.html";
const ROUNDS=[
 {title:"Taman Ceria",hint:"Bayangkan sebuah taman yang memiliki matahari, pohon, air, bunga, kupu-kupu, dan rumput.",pieces:[['sun','☀️','Matahari','Cahaya matahari membantu tanaman.'],['tree','🌳','Pohon','Pohon adalah tumbuhan yang penting bagi lingkungan.'],['water','💧','Air','Air membantu tumbuhan dan hewan hidup.'],['flower','🌼','Bunga','Bunga menjadi bagian indah dari tumbuhan.'],['butterfly','🦋','Kupu-kupu','Kupu-kupu adalah hewan yang dapat membantu proses penyerbukan.'],['grass','🌱','Rumput','Rumput adalah tumbuhan yang dapat hidup di taman.']]},
 {title:"Sungai Bersih",hint:"Cari susunan sungai: air, ikan, tanaman tepi sungai, matahari, batu, dan tempat sampah.",pieces:[['water','💧','Air','Sungai yang bersih membutuhkan air yang tidak tercemar.'],['fish','🐟','Ikan','Ikan membutuhkan air yang bersih untuk hidup.'],['plant','🌿','Tanaman','Tanaman di sekitar sungai ikut menjaga ekosistem.'],['sun','☀️','Matahari','Matahari adalah bagian dari lingkungan alami.'],['rock','🪨','Batu','Batu dapat menjadi bagian dari habitat sungai.'],['bin','🗑️','Tempat sampah','Tempat sampah membantu sampah tidak masuk ke sungai.']]},
 {title:"Hutan Hijau",hint:"Susun habitat hutan dengan pohon, burung, rusa, bunga, tanah, dan air.",pieces:[['tree','🌲','Pohon','Pohon menyediakan tempat hidup dan membantu udara tetap segar.'],['bird','🐦','Burung','Burung adalah bagian dari ekosistem hutan.'],['deer','🦌','Rusa','Rusa membutuhkan habitat yang aman.'],['flower','🌸','Bunga','Bunga menjadi bagian dari banyak ekosistem.'],['soil','🟫','Tanah','Tanah membantu tumbuhan tumbuh.'],['water','💧','Air','Makhluk hidup membutuhkan air.']]},
 {title:"Bumi Ramah",hint:"Bayangkan lingkungan sehat: bumi, pohon, tempat sampah, botol pakai ulang, sepeda, dan tas belanja.",pieces:[['earth','🌍','Bumi','Bumi adalah rumah kita bersama.'],['tree','🌳','Pohon','Pohon membantu lingkungan menjadi hijau.'],['bin','🗑️','Tempat sampah','Sampah perlu dikelola agar lingkungan bersih.'],['bottle','🥤','Botol pakai ulang','Botol pakai ulang dapat membantu mengurangi sampah sekali pakai.'],['bike','🚲','Sepeda','Bersepeda bisa menjadi pilihan ramah lingkungan untuk jarak dekat.'],['bag','👜','Tas pakai ulang','Tas pakai ulang membantu mengurangi penggunaan kantong sekali pakai.']]}
];
let session=null,timerHandle=null,hintTimer=null,selectedPieceId=null;
const $=id=>document.getElementById(id);const tutorialScreen=$("tutorialScreen"),gameArea=$("gameArea"),timeoutScreen=$("timeoutScreen"),progressText=$("progressText"),timerText=$("timerText"),roundTitle=$("roundTitle"),roundInstruction=$("roundInstruction"),referenceStrip=$("referenceStrip"),slots=$("slots"),pieces=$("pieces"),feedback=$("feedback"),feedbackIcon=$("feedbackIcon"),feedbackTitle=$("feedbackTitle"),feedbackText=$("feedbackText"),hintBox=$("hintBox");
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}function load(){try{return JSON.parse(localStorage.getItem(GAME_KEY)||"null")}catch{return null}}function save(){localStorage.setItem(GAME_KEY,JSON.stringify(session))}
function syncTime(){if(!session||session.status!=="playing")return;const now=Date.now(),elapsed=Math.floor((now-session.lastUpdatedAt)/1000);if(elapsed<=0)return;session.timeRemaining=Math.max(0,session.timeRemaining-elapsed);session.lastUpdatedAt=now;if(session.timeRemaining===0){session.status="timeup";save();showTimeout();return}save();updateHud()}
function startTimer(){clearInterval(timerHandle);syncTime();timerHandle=setInterval(syncTime,250);document.addEventListener("visibilitychange",syncTime)}
function updateHud(){progressText.textContent=`Ronde ${Math.min(ROUNDS.length,session.puzzle?.round+1||1)}/${ROUNDS.length}`;const sec=Math.max(0,session.timeRemaining);timerText.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;timerText.style.color=sec<=30?'#d65f50':sec<=60?'#bd8b23':''}
function showFeedback(icon,title,text,type){feedbackIcon.textContent=icon;feedbackTitle.textContent=title;feedbackText.textContent=text;feedback.className=`feedback ${type==='correct'?'correct-feedback':'wrong-feedback'}`}
function hideFeedback(){feedback.classList.add('hidden')}
function showHint(){const round=ROUNDS[session.puzzle.round];hintBox.textContent=`💡 ${round.hint}`;hintBox.classList.remove('hidden');clearTimeout(hintTimer);hintTimer=setTimeout(()=>hintBox.classList.add('hidden'),4800)}
function resetHint(){clearTimeout(hintTimer);hintBox.classList.add('hidden');hintTimer=setTimeout(()=>{if(session.status==='playing')showHint()},11000)}
function ensure(){session=load();if(!session||session.version!==4||session.currentChallenge!==CHALLENGE_NO){if(session&&session.currentChallenge>CHALLENGE_NO){location.href=`challenge${session.currentChallenge}.html`;return false}location.href='challenge1.html';return false}if(session.status==='timeup'||session.timeRemaining<=0){session.status='timeup';save();showTimeout();return false}return true}
function startChallenge(){session.challengeStarted[2]=true;session.status='playing';session.lastUpdatedAt=Date.now();if(!session.puzzle)session.puzzle={round:0,placed:{}};save();tutorialScreen.classList.add('hidden');gameArea.classList.remove('hidden');renderRound();updateHud();startTimer();resetHint()}
function renderRound(){
  const round=ROUNDS[session.puzzle.round];roundTitle.textContent=`🧩 Ronde ${session.puzzle.round+1}: ${round.title}`;roundInstruction.textContent=`Pasang ${round.pieces.length} potongan dengan benar.`;referenceStrip.innerHTML=round.pieces.map(p=>`<span title="${p[2]}">${p[1]}</span>`).join('');slots.innerHTML='';pieces.innerHTML='';selectedPieceId=null;
  const placed=session.puzzle.placed||{};
  round.pieces.forEach((p,index)=>{const slot=document.createElement('button');slot.type='button';slot.className=`puzzle-slot ${placed[index]?'filled':''}`;slot.dataset.slot=index;slot.innerHTML=placed[index]?`<span class="slot-filled-icon">${p[1]}</span><span class="slot-label">${p[2]}</span>`:`<span class="slot-placeholder">${p[1]}</span><span class="slot-label">Bagian ${index+1}</span>`;if(!placed[index])slot.addEventListener('click',()=>placeSelected(index));slots.appendChild(slot)});
  const order=shuffle(round.pieces.map((_,i)=>i));order.forEach(index=>{const p=round.pieces[index],el=document.createElement('button');el.type='button';el.className=`puzzle-piece ${placed[index]?'placed':''}`;el.dataset.piece=index;el.innerHTML=`<span class="piece-icon">${p[1]}</span><span class="piece-label">${p[2]}</span>`;if(!placed[index])el.addEventListener('click',()=>selectPiece(index,el));pieces.appendChild(el)});
  save();resetHint();
}
function selectPiece(index,el){if(session.status!=='playing')return;selectedPieceId=index;pieces.querySelectorAll('.puzzle-piece').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');resetHint()}
function placeSelected(slotIndex){if(selectedPieceId===null||session.status!=='playing')return;const round=ROUNDS[session.puzzle.round],p=round.pieces[selectedPieceId];clearTimeout(hintTimer);if(selectedPieceId===slotIndex){session.totalCorrect++;session.score+=5;session.puzzle.placed[slotIndex]=true;save();renderRound();showFeedback('🎉','Pas!',`${p[1]} ${p[2]} cocok ditempatkan di bagian ini. ${p[3]}`,'correct');setTimeout(()=>{hideFeedback();const done=Object.keys(session.puzzle.placed).length===round.pieces.length;if(done)nextRound();else resetHint()},650)}else{session.totalWrong++;save();showFeedback('💡','Belum cocok',`Coba periksa lagi susunannya. ${p[3]}`,'wrong');slots.querySelector(`[data-slot="${slotIndex}"]`)?.classList.add('selected-target');setTimeout(()=>{hideFeedback();slots.querySelector(`[data-slot="${slotIndex}"]`)?.classList.remove('selected-target');resetHint()},1100)}}
function nextRound(){session.puzzle.round++;session.puzzle.placed={};if(session.puzzle.round>=ROUNDS.length){completeChallenge();return}save();renderRound()}
function completeChallenge(){clearTimeout(hintTimer);session.completed[2]=true;session.score+=100;session.currentChallenge=4;session.challengeStarted[3]=false;session.status='instruction';session.lastUpdatedAt=Date.now();save();gameArea.classList.add('hidden');setTimeout(()=>location.href=nextPage,900)}
function showTimeout(){clearTimeout(hintTimer);clearInterval(timerHandle);gameArea.classList.add('hidden');tutorialScreen.classList.add('hidden');timeoutScreen.classList.remove('hidden')}
function restart(){localStorage.removeItem(GAME_KEY);location.href='challenge1.html'}
function checkStartup(){if(!ensure())return;updateHud();if(!session.puzzle)session.puzzle={round:0,placed:{}};if(session.status==='timeup')return;if(session.challengeStarted[2]){tutorialScreen.classList.add('hidden');gameArea.classList.remove('hidden');renderRound();startTimer()}else{tutorialScreen.classList.remove('hidden');gameArea.classList.add('hidden');clearInterval(timerHandle)}}
$("startChallengeBtn").addEventListener('click',startChallenge);$("hintBtn").addEventListener('click',()=>{if(session?.status==='playing')showHint()});document.querySelector('[data-restart]').addEventListener('click',restart);window.addEventListener('beforeunload',()=>{if(session){syncTime();save()}});checkStartup();
